;; -*- mode: eask; lexical-binding: t -*-

(package "muldoc"
         "0.4.0"
         "Multi ElDoc integration")

(website-url "https://github.com/emacs-php/muldoc")
(keywords "tools" "extension")

(package-file "muldoc.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)

(depends-on "emacs" "25.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
